# Generated by Django 3.0.5 on 2020-05-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunaconAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AuthorizedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('jobSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunaconAPI.JobSite')),
                ('orders', models.ManyToManyField(to='lunaconAPI.Order')),
            ],
        ),
    ]
