# Generated by Django 3.0.5 on 2020-06-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunaconAPI', '0002_order_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='lunaconAPI.Product_Order', to='lunaconAPI.Product'),
        ),
        migrations.AddField(
            model_name='product_order',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lunaconAPI.Order'),
            preserve_default=False,
        ),
    ]
