# Generated by Django 3.0.5 on 2020-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunaconAPI', '0003_auto_20200621_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
